name: Validate the repositories.py file

on:
  pull_request:
    paths:
      - repositories.py

jobs:
  validate-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Git user
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Merge PR into target branch
      run: git merge origin/${{ github.event.pull_request.base.ref }}
  
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Validate Python file
      run: python -m py_compile repositories.py

    - name: Check GitHub links validity
      run: |
        python -c "
        import json
        import os

        with open('repositories.py', 'r') as file:
            content = file.read()
            exec(content)

        for group in GROUP_REPOS:
            for link in group.get('gitLinks', []):
                if '/orgs/' not in link and '/repositories' not in link:
                    print(f'Checking {link}')
                    exit_code = os.system(f'curl -o /dev/null --silent --head --fail {link}')
                    if exit_code != 0:
                        raise Exception(f'Invalid link: {link}')
                else:
                    raise Exception(f'Links to /repositories instead of a specific repository: {link}')
              "
